apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: team-finance
  source:
    repoURL: https://github.com/jehadkalifah/argocd-example-apps.git
    path: helm-guestbook
    targetRevision: HEAD
  parameters:
    - name: namespace
      value: finance    
  destination:
    server: https://kubernetes.default.svc
    namespace: finance
